/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	titanclusterv1 "github.com/jlerche/titan-operator/pkg/apis/titancluster/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTitanClusters implements TitanClusterInterface
type FakeTitanClusters struct {
	Fake *FakeFooV1
	ns   string
}

var titanclustersResource = schema.GroupVersionResource{Group: "foo.com", Version: "v1", Resource: "titanclusters"}

var titanclustersKind = schema.GroupVersionKind{Group: "foo.com", Version: "v1", Kind: "TitanCluster"}

// Get takes name of the titanCluster, and returns the corresponding titanCluster object, and an error if there is any.
func (c *FakeTitanClusters) Get(name string, options v1.GetOptions) (result *titanclusterv1.TitanCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(titanclustersResource, c.ns, name), &titanclusterv1.TitanCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*titanclusterv1.TitanCluster), err
}

// List takes label and field selectors, and returns the list of TitanClusters that match those selectors.
func (c *FakeTitanClusters) List(opts v1.ListOptions) (result *titanclusterv1.TitanClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(titanclustersResource, titanclustersKind, c.ns, opts), &titanclusterv1.TitanClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &titanclusterv1.TitanClusterList{ListMeta: obj.(*titanclusterv1.TitanClusterList).ListMeta}
	for _, item := range obj.(*titanclusterv1.TitanClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested titanClusters.
func (c *FakeTitanClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(titanclustersResource, c.ns, opts))

}

// Create takes the representation of a titanCluster and creates it.  Returns the server's representation of the titanCluster, and an error, if there is any.
func (c *FakeTitanClusters) Create(titanCluster *titanclusterv1.TitanCluster) (result *titanclusterv1.TitanCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(titanclustersResource, c.ns, titanCluster), &titanclusterv1.TitanCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*titanclusterv1.TitanCluster), err
}

// Update takes the representation of a titanCluster and updates it. Returns the server's representation of the titanCluster, and an error, if there is any.
func (c *FakeTitanClusters) Update(titanCluster *titanclusterv1.TitanCluster) (result *titanclusterv1.TitanCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(titanclustersResource, c.ns, titanCluster), &titanclusterv1.TitanCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*titanclusterv1.TitanCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTitanClusters) UpdateStatus(titanCluster *titanclusterv1.TitanCluster) (*titanclusterv1.TitanCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(titanclustersResource, "status", c.ns, titanCluster), &titanclusterv1.TitanCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*titanclusterv1.TitanCluster), err
}

// Delete takes name of the titanCluster and deletes it. Returns an error if one occurs.
func (c *FakeTitanClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(titanclustersResource, c.ns, name), &titanclusterv1.TitanCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTitanClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(titanclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &titanclusterv1.TitanClusterList{})
	return err
}

// Patch applies the patch and returns the patched titanCluster.
func (c *FakeTitanClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *titanclusterv1.TitanCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(titanclustersResource, c.ns, name, pt, data, subresources...), &titanclusterv1.TitanCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*titanclusterv1.TitanCluster), err
}
